local ColorGui = require('highlight_builder.color')

---@alias PaletteCustomColorInput string | ColorGui

---@class PaletteCustomPrimary
---@field fg PaletteCustomColorInput
---@field bg PaletteCustomColorInput

---@class PaletteCustomColors
---@field black PaletteCustomColorInput
---@field red PaletteCustomColorInput
---@field green PaletteCustomColorInput
---@field yellow PaletteCustomColorInput
---@field blue PaletteCustomColorInput
---@field magenta PaletteCustomColorInput
---@field cyan PaletteCustomColorInput
---@field white PaletteCustomColorInput

---@class PaletteCustom
---@field primary PaletteCustomPrimary
---@field dark PaletteCustomColors
---@field bright PaletteCustomColors

local to_256 = {
    ColorGui.from_hex('#000000'),
    ColorGui.from_hex('#00005F'),
    ColorGui.from_hex('#000087'),
    ColorGui.from_hex('#0000AF'),
    ColorGui.from_hex('#0000D7'),
    ColorGui.from_hex('#0000FF'),
    ColorGui.from_hex('#005F00'),
    ColorGui.from_hex('#005F5F'),
    ColorGui.from_hex('#005F87'),
    ColorGui.from_hex('#005FAF'),
    ColorGui.from_hex('#005FD7'),
    ColorGui.from_hex('#005FFF'),
    ColorGui.from_hex('#008700'),
    ColorGui.from_hex('#00875F'),
    ColorGui.from_hex('#008787'),
    ColorGui.from_hex('#0087AF'),
    ColorGui.from_hex('#0087D7'),
    ColorGui.from_hex('#0087FF'),
    ColorGui.from_hex('#00AF00'),
    ColorGui.from_hex('#00AF5F'),
    ColorGui.from_hex('#00AF87'),
    ColorGui.from_hex('#00AFAF'),
    ColorGui.from_hex('#00AFD7'),
    ColorGui.from_hex('#00AFFF'),
    ColorGui.from_hex('#00D700'),
    ColorGui.from_hex('#00D75F'),
    ColorGui.from_hex('#00D787'),
    ColorGui.from_hex('#00D7AF'),
    ColorGui.from_hex('#00D7D7'),
    ColorGui.from_hex('#00D7FF'),
    ColorGui.from_hex('#00FF00'),
    ColorGui.from_hex('#00FF5F'),
    ColorGui.from_hex('#00FF87'),
    ColorGui.from_hex('#00FFAF'),
    ColorGui.from_hex('#00FFD7'),
    ColorGui.from_hex('#00FFFF'),
    ColorGui.from_hex('#5F0000'),
    ColorGui.from_hex('#5F005F'),
    ColorGui.from_hex('#5F0087'),
    ColorGui.from_hex('#5F00AF'),
    ColorGui.from_hex('#5F00D7'),
    ColorGui.from_hex('#5F00FF'),
    ColorGui.from_hex('#5F5F00'),
    ColorGui.from_hex('#5F5F5F'),
    ColorGui.from_hex('#5F5F87'),
    ColorGui.from_hex('#5F5FAF'),
    ColorGui.from_hex('#5F5FD7'),
    ColorGui.from_hex('#5F5FFF'),
    ColorGui.from_hex('#5F8700'),
    ColorGui.from_hex('#5F875F'),
    ColorGui.from_hex('#5F8787'),
    ColorGui.from_hex('#5F87AF'),
    ColorGui.from_hex('#5F87D7'),
    ColorGui.from_hex('#5F87FF'),
    ColorGui.from_hex('#5FAF00'),
    ColorGui.from_hex('#5FAF5F'),
    ColorGui.from_hex('#5FAF87'),
    ColorGui.from_hex('#5FAFAF'),
    ColorGui.from_hex('#5FAFD7'),
    ColorGui.from_hex('#5FAFFF'),
    ColorGui.from_hex('#5FD700'),
    ColorGui.from_hex('#5FD75F'),
    ColorGui.from_hex('#5FD787'),
    ColorGui.from_hex('#5FD7AF'),
    ColorGui.from_hex('#5FD7D7'),
    ColorGui.from_hex('#5FD7FF'),
    ColorGui.from_hex('#5FFF00'),
    ColorGui.from_hex('#5FFF5F'),
    ColorGui.from_hex('#5FFF87'),
    ColorGui.from_hex('#5FFFAF'),
    ColorGui.from_hex('#5FFFD7'),
    ColorGui.from_hex('#5FFFFF'),
    ColorGui.from_hex('#870000'),
    ColorGui.from_hex('#87005F'),
    ColorGui.from_hex('#870087'),
    ColorGui.from_hex('#8700AF'),
    ColorGui.from_hex('#8700D7'),
    ColorGui.from_hex('#8700FF'),
    ColorGui.from_hex('#875F00'),
    ColorGui.from_hex('#875F5F'),
    ColorGui.from_hex('#875F87'),
    ColorGui.from_hex('#875FAF'),
    ColorGui.from_hex('#875FD7'),
    ColorGui.from_hex('#875FFF'),
    ColorGui.from_hex('#878700'),
    ColorGui.from_hex('#87875F'),
    ColorGui.from_hex('#878787'),
    ColorGui.from_hex('#8787AF'),
    ColorGui.from_hex('#8787D7'),
    ColorGui.from_hex('#8787FF'),
    ColorGui.from_hex('#87AF00'),
    ColorGui.from_hex('#87AF5F'),
    ColorGui.from_hex('#87AF87'),
    ColorGui.from_hex('#87AFAF'),
    ColorGui.from_hex('#87AFD7'),
    ColorGui.from_hex('#87AFFF'),
    ColorGui.from_hex('#87D700'),
    ColorGui.from_hex('#87D75F'),
    ColorGui.from_hex('#87D787'),
    ColorGui.from_hex('#87D7AF'),
    ColorGui.from_hex('#87D7D7'),
    ColorGui.from_hex('#87D7FF'),
    ColorGui.from_hex('#87FF00'),
    ColorGui.from_hex('#87FF5F'),
    ColorGui.from_hex('#87FF87'),
    ColorGui.from_hex('#87FFAF'),
    ColorGui.from_hex('#87FFD7'),
    ColorGui.from_hex('#87FFFF'),
    ColorGui.from_hex('#AF0000'),
    ColorGui.from_hex('#AF005F'),
    ColorGui.from_hex('#AF0087'),
    ColorGui.from_hex('#AF00AF'),
    ColorGui.from_hex('#AF00D7'),
    ColorGui.from_hex('#AF00FF'),
    ColorGui.from_hex('#AF5F00'),
    ColorGui.from_hex('#AF5F5F'),
    ColorGui.from_hex('#AF5F87'),
    ColorGui.from_hex('#AF5FAF'),
    ColorGui.from_hex('#AF5FD7'),
    ColorGui.from_hex('#AF5FFF'),
    ColorGui.from_hex('#AF8700'),
    ColorGui.from_hex('#AF875F'),
    ColorGui.from_hex('#AF8787'),
    ColorGui.from_hex('#AF87AF'),
    ColorGui.from_hex('#AF87D7'),
    ColorGui.from_hex('#AF87FF'),
    ColorGui.from_hex('#AFAF00'),
    ColorGui.from_hex('#AFAF5F'),
    ColorGui.from_hex('#AFAF87'),
    ColorGui.from_hex('#AFAFAF'),
    ColorGui.from_hex('#AFAFD7'),
    ColorGui.from_hex('#AFAFFF'),
    ColorGui.from_hex('#AFD700'),
    ColorGui.from_hex('#AFD75F'),
    ColorGui.from_hex('#AFD787'),
    ColorGui.from_hex('#AFD7AF'),
    ColorGui.from_hex('#AFD7D7'),
    ColorGui.from_hex('#AFD7FF'),
    ColorGui.from_hex('#AFFF00'),
    ColorGui.from_hex('#AFFF5F'),
    ColorGui.from_hex('#AFFF87'),
    ColorGui.from_hex('#AFFFAF'),
    ColorGui.from_hex('#AFFFD7'),
    ColorGui.from_hex('#AFFFFF'),
    ColorGui.from_hex('#D70000'),
    ColorGui.from_hex('#D7005F'),
    ColorGui.from_hex('#D70087'),
    ColorGui.from_hex('#D700AF'),
    ColorGui.from_hex('#D700D7'),
    ColorGui.from_hex('#D700FF'),
    ColorGui.from_hex('#D75F00'),
    ColorGui.from_hex('#D75F5F'),
    ColorGui.from_hex('#D75F87'),
    ColorGui.from_hex('#D75FAF'),
    ColorGui.from_hex('#D75FD7'),
    ColorGui.from_hex('#D75FFF'),
    ColorGui.from_hex('#D78700'),
    ColorGui.from_hex('#D7875F'),
    ColorGui.from_hex('#D78787'),
    ColorGui.from_hex('#D787AF'),
    ColorGui.from_hex('#D787D7'),
    ColorGui.from_hex('#D787FF'),
    ColorGui.from_hex('#D7AF00'),
    ColorGui.from_hex('#D7AF5F'),
    ColorGui.from_hex('#D7AF87'),
    ColorGui.from_hex('#D7AFAF'),
    ColorGui.from_hex('#D7AFD7'),
    ColorGui.from_hex('#D7AFFF'),
    ColorGui.from_hex('#D7D700'),
    ColorGui.from_hex('#D7D75F'),
    ColorGui.from_hex('#D7D787'),
    ColorGui.from_hex('#D7D7AF'),
    ColorGui.from_hex('#D7D7D7'),
    ColorGui.from_hex('#D7D7FF'),
    ColorGui.from_hex('#D7FF00'),
    ColorGui.from_hex('#D7FF5F'),
    ColorGui.from_hex('#D7FF87'),
    ColorGui.from_hex('#D7FFAF'),
    ColorGui.from_hex('#D7FFD7'),
    ColorGui.from_hex('#D7FFFF'),
    ColorGui.from_hex('#FF0000'),
    ColorGui.from_hex('#FF005F'),
    ColorGui.from_hex('#FF0087'),
    ColorGui.from_hex('#FF00AF'),
    ColorGui.from_hex('#FF00D7'),
    ColorGui.from_hex('#FF00FF'),
    ColorGui.from_hex('#FF5F00'),
    ColorGui.from_hex('#FF5F5F'),
    ColorGui.from_hex('#FF5F87'),
    ColorGui.from_hex('#FF5FAF'),
    ColorGui.from_hex('#FF5FD7'),
    ColorGui.from_hex('#FF5FFF'),
    ColorGui.from_hex('#FF8700'),
    ColorGui.from_hex('#FF875F'),
    ColorGui.from_hex('#FF8787'),
    ColorGui.from_hex('#FF87AF'),
    ColorGui.from_hex('#FF87D7'),
    ColorGui.from_hex('#FF87FF'),
    ColorGui.from_hex('#FFAF00'),
    ColorGui.from_hex('#FFAF5F'),
    ColorGui.from_hex('#FFAF87'),
    ColorGui.from_hex('#FFAFAF'),
    ColorGui.from_hex('#FFAFD7'),
    ColorGui.from_hex('#FFAFFF'),
    ColorGui.from_hex('#FFD700'),
    ColorGui.from_hex('#FFD75F'),
    ColorGui.from_hex('#FFD787'),
    ColorGui.from_hex('#FFD7AF'),
    ColorGui.from_hex('#FFD7D7'),
    ColorGui.from_hex('#FFD7FF'),
    ColorGui.from_hex('#FFFF00'),
    ColorGui.from_hex('#FFFF5F'),
    ColorGui.from_hex('#FFFF87'),
    ColorGui.from_hex('#FFFFAF'),
    ColorGui.from_hex('#FFFFD7'),
    ColorGui.from_hex('#FFFFFF'),
    ColorGui.from_hex('#080808'),
    ColorGui.from_hex('#121212'),
    ColorGui.from_hex('#1C1C1C'),
    ColorGui.from_hex('#262626'),
    ColorGui.from_hex('#303030'),
    ColorGui.from_hex('#3A3A3A'),
    ColorGui.from_hex('#444444'),
    ColorGui.from_hex('#4E4E4E'),
    ColorGui.from_hex('#585858'),
    ColorGui.from_hex('#626262'),
    ColorGui.from_hex('#6C6C6C'),
    ColorGui.from_hex('#767676'),
    ColorGui.from_hex('#808080'),
    ColorGui.from_hex('#8A8A8A'),
    ColorGui.from_hex('#949494'),
    ColorGui.from_hex('#9E9E9E'),
    ColorGui.from_hex('#A8A8A8'),
    ColorGui.from_hex('#B2B2B2'),
    ColorGui.from_hex('#BCBCBC'),
    ColorGui.from_hex('#C6C6C6'),
    ColorGui.from_hex('#D0D0D0'),
    ColorGui.from_hex('#DADADA'),
    ColorGui.from_hex('#E4E4E4'),
    ColorGui.from_hex('#EEEEEE'),
}

---@param c PaletteCustomColorInput
---@return ColorGui
local function color(c)
    if type(c) == 'string' then
        return ColorGui.from_hex(c)
    end
    ---@cast c ColorGui
    return c
end

---@param palette PaletteCustom
---@param complete_to_256 boolean
---@return Palette
return function(palette, complete_to_256)
    ---@type Palette
    local p = {
        primary = {
            fg = color(palette.primary.fg),
            bg = color(palette.primary.bg),
        },
        indexed = {
            color(palette.dark.black),
            color(palette.dark.red),
            color(palette.dark.green),
            color(palette.dark.yellow),
            color(palette.dark.blue),
            color(palette.dark.magenta),
            color(palette.dark.cyan),
            color(palette.dark.white),
            color(palette.bright.black),
            color(palette.bright.red),
            color(palette.bright.green),
            color(palette.bright.yellow),
            color(palette.bright.blue),
            color(palette.bright.magenta),
            color(palette.bright.cyan),
            color(palette.bright.white),
        },
    }

    if complete_to_256 then
        for _, c in ipairs(to_256) do
            p.indexed[#p.indexed + 1] = c
        end
    end

    return p
end
