name: CI

on:
    push:
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                nvim_branch:
                    - 'stable'
                    - 'nightly'

        env:
            NVIM_VERSION: ${{ matrix.nvim_branch }}

        steps:
            -
                name: Checkout
                uses: actions/checkout@v3

            -
                name: Install Lua
                uses: leafo/gh-actions-lua@v10
                with:
                    luaVersion: "5.1.5"

            -
                name: Install LuaRocks
                uses: leafo/gh-actions-luarocks@v4

            -
                name: Install Neovim
                run: |
                    # Download
                    NVIM_URL=https://github.com/neovim/neovim/releases/download
                    wget "${NVIM_URL}/${NVIM_VERSION}/nvim-linux64.tar.gz"
                    tar -xf "nvim-linux64.tar.gz"
                    # Install
                    sudo cp "./nvim-linux64/bin/nvim" "/bin/"
                    # Clean up
                    rm -rf "./nvim-linux64.tar.gz"
                    rm -rf "./nvim-linux64"

            -
                name: Run tests
                run:
                    ./test.sh


